spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?serverTimezone=Asia/Shanghai
    username: root
    password: 123123
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080