spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?serverTimezone=Asia/Shanghai
    username: root
    password: 123123
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.137.20
    port: 6379
    database: 0
    #    这里我采用了lettuce连接池，听狂神说这个更好
    jedis:
      pool:
        max-active: 50
        min-idle: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080