server:
  port: 80
  tomcat:
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100
    accesslog:
      enabled: true
      directory: /var/www/miaosha/tomcat
#h:remote_host_ip, u:remote_user t:handle_cost_time r:request_url s:http_return:code b:bytes_send D:handle_cost_time
      pattern: '%h %l %u %t "%r" %s %b %D'
spring:
  datasource:
    url: jdbc:mysql://192.168.137.20:3306/miaosha?serverTimezone=Asia/Shanghai