spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  profiles:
    active: sci
server:
  tomcat:
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

